#8ヘッダーをboostrapにしました。#21にあるよう内容がかみ合ってないので、ヘッダーの内容は一時的にindex.htmlのヘッダー…
rc-project/pr-app-development pull request #24
Opened 2017-10-26 06:41 UTC by ChihiroEndo0808

…の内容で統一しています。

2017-10-26 12:17 UTC, yuu7975 requested changes

2017-10-26 12:17 UTC, yuu7975 commented on info.html
> +        <a class="nav-link" href="info.html">トップページ</a>
info.htmlがトップページでいいの？

2017-10-26 12:20 UTC, ChihiroEndo0808 commented on info.html
> +        <a class="nav-link" href="info.html">トップページ</a>
index.htmlでinfo.htmlがトップページになっていたので、今回はそちらに合わせてます。

2017-10-26 12:21 UTC, ChihiroEndo0808 commented on info.html
> +        <a class="nav-link" href="info.html">トップページ</a>
連投ですいません、#21でまとめてファイル名と内容を一致させるとあったので、その際に修正しようと考えています。

2017-10-26 12:25 UTC, yuu7975 commented on info.html
> +        <a class="nav-link" href="info.html">トップページ</a>
了解です

2017-10-26 12:25 UTC, yuu7975 approved these changes

2017-10-27 01:45 UTC, miyzawa approved these changes

2017-10-27 02:31 UTC, merged